NODE_TYPE_DICT = {
    'paper': 'This node represents a paper',
    'venue': 'This node represents a venue (could be a journal, conference, repository or patent)',
    'field': 'This node represents a field of study (could be L0, L1, L2, L3, L4 or L5)',
    'author': 'This node represents an author',
    'affiliation': 'This node represents an affiliation (could be a university, company or institution)',
}

EDGE_TYPE_DICT = {
('paper', 'PV_Conference', 'venue'): 'The paper is published in the conference', 
('venue', 'Inverse_PV_Conference', 'paper'): 'The conference has the paper', 
('paper', 'PV_Journal', 'venue'): 'The paper is published in the journal', 
('venue', 'Inverse_PV_Journal', 'paper'): 'The journal has the paper', 
('paper', 'PV_Repository', 'venue'): 'The paper is published in the repository', 
('venue', 'Inverse_PV_Repository', 'paper'): 'The repository has the paper', 
('paper', 'PV_Patent', 'venue'): 'The paper is published in the patent', 
('venue', 'Inverse_PV_Patent', 'paper'): 'The patent has the paper', 
('paper', 'PP_cite', 'paper'): 'The paper cites the paper', 
('paper', 'Inverse_PP_cite', 'paper'): 'The paper is cited by the paper', 
('author', 'AP_write_last', 'paper'): 'The author is the last author of the paper', 
('paper', 'Inverse_AP_write_last', 'author'): 'The paper lists the author as its last author', 
('author', 'AP_write_other', 'paper'): 'The author is neither the first nor the last author of the paper', 
('paper', 'Inverse_AP_write_other', 'author'): 'The paper lists the author as neither its first nor its last author', 
('author', 'AP_write_first', 'paper'): 'The author is the first author of the paper', 
('paper', 'Inverse_AP_write_first', 'author'): 'The paper lists the author as its first author', 
('field', 'FF_in', 'field'): 'The field is in the field', 
('field', 'Inverse_FF_in', 'field'): 'The field includes the field', 
('paper', 'PF_in_L0', 'field'): 'The paper belongs to the L0 field', 
('field', 'Inverse_PF_in_L0', 'paper'): 'The L0 field includes the paper', 
('paper', 'PF_in_L3', 'field'): 'The paper belongs to the L3 field', 
('field', 'Inverse_PF_in_L3', 'paper'): 'The L3 field includes the paper', 
('paper', 'PF_in_L2', 'field'): 'The paper belongs to the L2 field', 
('field', 'Inverse_PF_in_L2', 'paper'): 'The L2 field includes the paper', 
('paper', 'PF_in_L5', 'field'): 'The paper belongs to the L5 field', 
('field', 'Inverse_PF_in_L5', 'paper'): 'The L5 field includes the paper', 
('paper', 'PF_in_L4', 'field'): 'The paper belongs to the L4 field', 
('field', 'Inverse_PF_in_L4', 'paper'): 'The L4 field includes the paper', 
('author', 'in', 'affiliation'): 'The author is affiliated with the affiliation', 
('affiliation', 'Inverse_in', 'author'): 'The affiliation has the author', 
}